# sc-ssd.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gold-sc
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  fsType: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate


---

# pvc-ssd.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gold-sc-pvc
spec:
  storageClassName: gold-sc #Using Storage Class created in step-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
